/* GENERATED by scripts/build_audio.py — do not edit by hand. */
import type { Timing } from "../whiteboard/types";

/**
 * Placeholder so the project type-checks before the first build.
 * Run `python3 scripts/build_audio.py` to replace it with the real timeline.
 */
export const TIMING: Timing = {
  "fps": 30,
  "width": 1080,
  "height": 1920,
  "durationInFrames": 90,
  "audioTrack": "narration.wav",
  "lines": [],
  "scenes": [],
};
